version: "3.7"

services:
  #  search:
  #    container_name: search
  #    image: search:latest
  #    ports:
  #      - "8080:8080"

  redis:
    container_name: search-cache
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: search-queue
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
