spring:
  application:
    name: searhc
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  cache:
    type: redis

  redis:
    host: localhost
    port: 6371
    database: 0
    ttl-second: 10
  
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:search;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:

kakao:
  url: https://dapi.kakao.com/v2/search/blog
  key: -