spring:
  application:
    name: search
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  cache:
    type: redis

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:search;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:

blog:
  kakao:
    url: https://dapi.kakao.com/v2/search/blog
    key: x

  naver:
    url: https://openapi.naver.com/v1/search/blog.json
    id: x
    secret: x

---
spring:
  config.activate.on-profile: local
  jpa.show-sql: true
  redis:
    host: localhost
    port: 6371
    database: 0
    ttl-second: 120
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config.activate.on-profile: test
  jpa.show-sql: false
  redis:
    host: localhost
    port: 6371
    database: 0
    ttl-second: 600
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config.activate.on-profile: development
  jpa.show-sql: false
  redis:
    host: search-cache
    port: 6371
    database: 0
    ttl-second: 120
  rabbitmq:
    host: search-queue
    port: 5672
    username: guest
    password: guest